### ISSUE TITLE
network-config needs Netplan mac address match for DHCP to work on latest Ubuntu 22.04.3 LTS image

### ISSUE THREAD

**Issue by thedude42** [ghik/kubernetes-the-harder-way#3]
When following the steps in 02_Preparing_Environment_for_a_VM_Cluster.md I wasn't able to get DHCP when booting the `gateway` host. I was always timing out in the `systemd-networkd-wait-online.service` unit. When looking in to the host I could see the interface was not configured although it did have the correct MAC address configured `52:52:52:00:00:00`.

Manually running the `dhclient` immediately configured the interface correctly with the expected `192.168.1.10` address and DNS set to `192.168.1.1`.

After a bit of digging around I noticed that the cloud-init generated Netplan config looked something like this:

```
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        enp0s1:
            dhcp4: true
            match:
                macaddress: '52:00:00:12:34:56'
            set-name: enp0s1
    version: 2
```
When I executed `netplan status` the output indicated that the `enp0s1` interface was not configured and `netplan try` did not configure it either, which was not surprising given the MAC address that was configured. I changed the `mcaddress` entry to match the one actually assigned to enp0s1 and then `netplan try` successfully configured the interface and DHCP was able to assign the expected address.

After looking up the netplan configuration in the cloud-init docs https://cloudinit.readthedocs.io/en/22.3/topics/network-config-format-v2.html I re-generated the `gateway` configuration to original and tried changing the `gateway/network-config` to the following:

```
network:
  version: 2
  ethernets:
    enp0s1:
      dhcp4: true
      match:
        macaddress: 52:52:52:00:00:00
```

Re-launching the `gateway` host with this configuration fixed the issue and now the VM received DHCP during boot-up.

Wondering if this is something in active development with respect to the `vmsetup.sh` script and the `cloud-init/network-config.*` templates? Seems like this works as a template with the `vmsetup.sh` script:

```
network:
  version: 2
  ethernets:
    enp0s1:
      dhcp4: true
      match:
        macaddress: 52:52:52:00:00:$(printf "%02x\n" $vmid)
```

**Comment by ghik** [comment]
Hi, if you're going through the chapters the "long" way, then by the second chapter you should not have any `network-config`s yet. They only come into use in the fifth chapter, to set up Kubernetes API load balancer.

Without any `network-config`, the guest machine defaults to DHCP and should get the correct IP.

As for the current template for `network-config.gateway`, it looks like this:

```
network:
  version: 2
  ethernets:
    lo:
      match:
        name: lo
      addresses: [192.168.1.21/32]
    eth:
      match:
        name: enp*
      dhcp4: true
```

You may have been unfortunate enough to check out some previous version (probably somewhat accidentally pushed by me). But regardless of that, if you're going though the guide chapter by chapter, you shouldn't use scripts and templates from the repository. They serve more like a reference of what you end up with after completing _all_ the chapters.
